// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using book_store;

#nullable disable

namespace book_store.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20251209174806_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("book_store.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BookIsbn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BookISBN");

                    b.Property<string>("CoverLink")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BookId")
                        .HasName("PK__Books__3DE0C2277D470D70");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("book_store.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFB8B0C7CC");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("book_store.Models.RelOrderBook", b =>
                {
                    b.Property<int>("RelOrderBooksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("relOrderBooksID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelOrderBooksId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.HasKey("RelOrderBooksId")
                        .HasName("PK__relOrder__87FB36DA059F26EA");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("relOrderBooks", (string)null);
                });

            modelBuilder.Entity("book_store.Models.RelOrderBook", b =>
                {
                    b.HasOne("book_store.Models.Book", "Book")
                        .WithMany("RelOrderBooks")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("FK__relOrderB__BookI__3C69FB99");

                    b.HasOne("book_store.Models.Order", "Order")
                        .WithMany("RelOrderBooks")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__relOrderB__Order__3B75D760");

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("book_store.Models.Book", b =>
                {
                    b.Navigation("RelOrderBooks");
                });

            modelBuilder.Entity("book_store.Models.Order", b =>
                {
                    b.Navigation("RelOrderBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
